services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    depends_on:
        - db
    build:  
      context: ./app
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/app
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/application/logs
